version: "3.8"
services:
  db:
    image: postgres:15.2-alpine 
    ports:
      - "5432:5432"
    volumes:
      - beans-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

volumes:
  beans-data: